version: 2
updates
  - package-ecosystem: pip
    directory: /apps/api
    schedule:
      interval: weekly
    labels:
      - security

  - package-ecosystem: npm
    directory: /apps/app
    schedule:
      interval: weekly
    labels:
      - security

  - package-ecosystem: npm
    directory: /apps/web
    schedule:
      interval: weekly
    labels:
      - security

  - package-ecosystem: docker
    directory: /infra/docker
    schedule:
      interval: weekly
    labels:
      - security