version: 2
updates:
  - package-ecosystem: pip
    directory: /api
    schedule:
      interval: weekly
    labels:
      - security

  - package-ecosystem: docker
    directory: /api
    schedule:
      interval: weekly
    labels:
      - security

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - security
