/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConfirmEmailChangeRouteImport } from './routes/confirm-email-change'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSetupRouteImport } from './routes/_auth/setup'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppOrganiserRouteImport } from './routes/_app/organiser'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as AppTicketsIndexRouteImport } from './routes/_app/tickets/index'
import { Route as AppProfileIndexRouteImport } from './routes/_app/profile/index'
import { Route as AppOrganiserIndexRouteImport } from './routes/_app/organiser/index'
import { Route as AppHomeIndexRouteImport } from './routes/_app/home/index'
import { Route as AppEventsIndexRouteImport } from './routes/_app/events/index'
import { Route as AppTicketsTicketIdRouteImport } from './routes/_app/tickets/$ticketId'
import { Route as AppProfilePasskeysRouteImport } from './routes/_app/profile/passkeys'
import { Route as AppReservationsReservationIdIndexRouteImport } from './routes/_app/reservations/$reservationId/index'
import { Route as AppOrganiserOrgIdIndexRouteImport } from './routes/_app/organiser/$orgId/index'
import { Route as AppEventsEventIdIndexRouteImport } from './routes/_app/events/$eventId/index'
import { Route as AppEventsEventIdQueueRouteImport } from './routes/_app/events/$eventId/queue'
import { Route as AppEventsEventIdCheckoutRouteImport } from './routes/_app/events/$eventId/checkout'
import { Route as AppOrganiserOrgIdVenuesNewRouteImport } from './routes/_app/organiser/$orgId/venues/new'
import { Route as AppOrganiserOrgIdEventsNewRouteImport } from './routes/_app/organiser/$orgId/events/new'
import { Route as AppOrganiserOrgIdEventsEventIdIndexRouteImport } from './routes/_app/organiser/$orgId/events/$eventId/index'

const ConfirmEmailChangeRoute = ConfirmEmailChangeRouteImport.update({
  id: '/confirm-email-change',
  path: '/confirm-email-change',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSetupRoute = AuthSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppOrganiserRoute = AppOrganiserRouteImport.update({
  id: '/organiser',
  path: '/organiser',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppTicketsIndexRoute = AppTicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganiserIndexRoute = AppOrganiserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrganiserRoute,
} as any)
const AppHomeIndexRoute = AppHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppRoute,
} as any)
const AppTicketsTicketIdRoute = AppTicketsTicketIdRouteImport.update({
  id: '/tickets/$ticketId',
  path: '/tickets/$ticketId',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilePasskeysRoute = AppProfilePasskeysRouteImport.update({
  id: '/profile/passkeys',
  path: '/profile/passkeys',
  getParentRoute: () => AppRoute,
} as any)
const AppReservationsReservationIdIndexRoute =
  AppReservationsReservationIdIndexRouteImport.update({
    id: '/reservations/$reservationId/',
    path: '/reservations/$reservationId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrganiserOrgIdIndexRoute = AppOrganiserOrgIdIndexRouteImport.update({
  id: '/$orgId/',
  path: '/$orgId/',
  getParentRoute: () => AppOrganiserRoute,
} as any)
const AppEventsEventIdIndexRoute = AppEventsEventIdIndexRouteImport.update({
  id: '/events/$eventId/',
  path: '/events/$eventId/',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsEventIdQueueRoute = AppEventsEventIdQueueRouteImport.update({
  id: '/events/$eventId/queue',
  path: '/events/$eventId/queue',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsEventIdCheckoutRoute =
  AppEventsEventIdCheckoutRouteImport.update({
    id: '/events/$eventId/checkout',
    path: '/events/$eventId/checkout',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrganiserOrgIdVenuesNewRoute =
  AppOrganiserOrgIdVenuesNewRouteImport.update({
    id: '/$orgId/venues/new',
    path: '/$orgId/venues/new',
    getParentRoute: () => AppOrganiserRoute,
  } as any)
const AppOrganiserOrgIdEventsNewRoute =
  AppOrganiserOrgIdEventsNewRouteImport.update({
    id: '/$orgId/events/new',
    path: '/$orgId/events/new',
    getParentRoute: () => AppOrganiserRoute,
  } as any)
const AppOrganiserOrgIdEventsEventIdIndexRoute =
  AppOrganiserOrgIdEventsEventIdIndexRouteImport.update({
    id: '/$orgId/events/$eventId/',
    path: '/$orgId/events/$eventId/',
    getParentRoute: () => AppOrganiserRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirm-email-change': typeof ConfirmEmailChangeRoute
  '/$': typeof AppSplatRoute
  '/organiser': typeof AppOrganiserRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/setup': typeof AuthSetupRoute
  '/profile/passkeys': typeof AppProfilePasskeysRoute
  '/tickets/$ticketId': typeof AppTicketsTicketIdRoute
  '/events/': typeof AppEventsIndexRoute
  '/home/': typeof AppHomeIndexRoute
  '/organiser/': typeof AppOrganiserIndexRoute
  '/profile/': typeof AppProfileIndexRoute
  '/tickets/': typeof AppTicketsIndexRoute
  '/events/$eventId/checkout': typeof AppEventsEventIdCheckoutRoute
  '/events/$eventId/queue': typeof AppEventsEventIdQueueRoute
  '/events/$eventId/': typeof AppEventsEventIdIndexRoute
  '/organiser/$orgId/': typeof AppOrganiserOrgIdIndexRoute
  '/reservations/$reservationId/': typeof AppReservationsReservationIdIndexRoute
  '/organiser/$orgId/events/new': typeof AppOrganiserOrgIdEventsNewRoute
  '/organiser/$orgId/venues/new': typeof AppOrganiserOrgIdVenuesNewRoute
  '/organiser/$orgId/events/$eventId/': typeof AppOrganiserOrgIdEventsEventIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirm-email-change': typeof ConfirmEmailChangeRoute
  '/$': typeof AppSplatRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/setup': typeof AuthSetupRoute
  '/profile/passkeys': typeof AppProfilePasskeysRoute
  '/tickets/$ticketId': typeof AppTicketsTicketIdRoute
  '/events': typeof AppEventsIndexRoute
  '/home': typeof AppHomeIndexRoute
  '/organiser': typeof AppOrganiserIndexRoute
  '/profile': typeof AppProfileIndexRoute
  '/tickets': typeof AppTicketsIndexRoute
  '/events/$eventId/checkout': typeof AppEventsEventIdCheckoutRoute
  '/events/$eventId/queue': typeof AppEventsEventIdQueueRoute
  '/events/$eventId': typeof AppEventsEventIdIndexRoute
  '/organiser/$orgId': typeof AppOrganiserOrgIdIndexRoute
  '/reservations/$reservationId': typeof AppReservationsReservationIdIndexRoute
  '/organiser/$orgId/events/new': typeof AppOrganiserOrgIdEventsNewRoute
  '/organiser/$orgId/venues/new': typeof AppOrganiserOrgIdVenuesNewRoute
  '/organiser/$orgId/events/$eventId': typeof AppOrganiserOrgIdEventsEventIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/confirm-email-change': typeof ConfirmEmailChangeRoute
  '/_app/$': typeof AppSplatRoute
  '/_app/organiser': typeof AppOrganiserRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/setup': typeof AuthSetupRoute
  '/_app/profile/passkeys': typeof AppProfilePasskeysRoute
  '/_app/tickets/$ticketId': typeof AppTicketsTicketIdRoute
  '/_app/events/': typeof AppEventsIndexRoute
  '/_app/home/': typeof AppHomeIndexRoute
  '/_app/organiser/': typeof AppOrganiserIndexRoute
  '/_app/profile/': typeof AppProfileIndexRoute
  '/_app/tickets/': typeof AppTicketsIndexRoute
  '/_app/events/$eventId/checkout': typeof AppEventsEventIdCheckoutRoute
  '/_app/events/$eventId/queue': typeof AppEventsEventIdQueueRoute
  '/_app/events/$eventId/': typeof AppEventsEventIdIndexRoute
  '/_app/organiser/$orgId/': typeof AppOrganiserOrgIdIndexRoute
  '/_app/reservations/$reservationId/': typeof AppReservationsReservationIdIndexRoute
  '/_app/organiser/$orgId/events/new': typeof AppOrganiserOrgIdEventsNewRoute
  '/_app/organiser/$orgId/venues/new': typeof AppOrganiserOrgIdVenuesNewRoute
  '/_app/organiser/$orgId/events/$eventId/': typeof AppOrganiserOrgIdEventsEventIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirm-email-change'
    | '/$'
    | '/organiser'
    | '/login'
    | '/register'
    | '/setup'
    | '/profile/passkeys'
    | '/tickets/$ticketId'
    | '/events/'
    | '/home/'
    | '/organiser/'
    | '/profile/'
    | '/tickets/'
    | '/events/$eventId/checkout'
    | '/events/$eventId/queue'
    | '/events/$eventId/'
    | '/organiser/$orgId/'
    | '/reservations/$reservationId/'
    | '/organiser/$orgId/events/new'
    | '/organiser/$orgId/venues/new'
    | '/organiser/$orgId/events/$eventId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirm-email-change'
    | '/$'
    | '/login'
    | '/register'
    | '/setup'
    | '/profile/passkeys'
    | '/tickets/$ticketId'
    | '/events'
    | '/home'
    | '/organiser'
    | '/profile'
    | '/tickets'
    | '/events/$eventId/checkout'
    | '/events/$eventId/queue'
    | '/events/$eventId'
    | '/organiser/$orgId'
    | '/reservations/$reservationId'
    | '/organiser/$orgId/events/new'
    | '/organiser/$orgId/venues/new'
    | '/organiser/$orgId/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/confirm-email-change'
    | '/_app/$'
    | '/_app/organiser'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/setup'
    | '/_app/profile/passkeys'
    | '/_app/tickets/$ticketId'
    | '/_app/events/'
    | '/_app/home/'
    | '/_app/organiser/'
    | '/_app/profile/'
    | '/_app/tickets/'
    | '/_app/events/$eventId/checkout'
    | '/_app/events/$eventId/queue'
    | '/_app/events/$eventId/'
    | '/_app/organiser/$orgId/'
    | '/_app/reservations/$reservationId/'
    | '/_app/organiser/$orgId/events/new'
    | '/_app/organiser/$orgId/venues/new'
    | '/_app/organiser/$orgId/events/$eventId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ConfirmEmailChangeRoute: typeof ConfirmEmailChangeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/confirm-email-change': {
      id: '/confirm-email-change'
      path: '/confirm-email-change'
      fullPath: '/confirm-email-change'
      preLoaderRoute: typeof ConfirmEmailChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/setup': {
      id: '/_auth/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthSetupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/organiser': {
      id: '/_app/organiser'
      path: '/organiser'
      fullPath: '/organiser'
      preLoaderRoute: typeof AppOrganiserRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tickets/': {
      id: '/_app/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof AppTicketsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/': {
      id: '/_app/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organiser/': {
      id: '/_app/organiser/'
      path: '/'
      fullPath: '/organiser/'
      preLoaderRoute: typeof AppOrganiserIndexRouteImport
      parentRoute: typeof AppOrganiserRoute
    }
    '/_app/home/': {
      id: '/_app/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof AppHomeIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/': {
      id: '/_app/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tickets/$ticketId': {
      id: '/_app/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof AppTicketsTicketIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/passkeys': {
      id: '/_app/profile/passkeys'
      path: '/profile/passkeys'
      fullPath: '/profile/passkeys'
      preLoaderRoute: typeof AppProfilePasskeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reservations/$reservationId/': {
      id: '/_app/reservations/$reservationId/'
      path: '/reservations/$reservationId'
      fullPath: '/reservations/$reservationId/'
      preLoaderRoute: typeof AppReservationsReservationIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organiser/$orgId/': {
      id: '/_app/organiser/$orgId/'
      path: '/$orgId'
      fullPath: '/organiser/$orgId/'
      preLoaderRoute: typeof AppOrganiserOrgIdIndexRouteImport
      parentRoute: typeof AppOrganiserRoute
    }
    '/_app/events/$eventId/': {
      id: '/_app/events/$eventId/'
      path: '/events/$eventId'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof AppEventsEventIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/$eventId/queue': {
      id: '/_app/events/$eventId/queue'
      path: '/events/$eventId/queue'
      fullPath: '/events/$eventId/queue'
      preLoaderRoute: typeof AppEventsEventIdQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/$eventId/checkout': {
      id: '/_app/events/$eventId/checkout'
      path: '/events/$eventId/checkout'
      fullPath: '/events/$eventId/checkout'
      preLoaderRoute: typeof AppEventsEventIdCheckoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organiser/$orgId/venues/new': {
      id: '/_app/organiser/$orgId/venues/new'
      path: '/$orgId/venues/new'
      fullPath: '/organiser/$orgId/venues/new'
      preLoaderRoute: typeof AppOrganiserOrgIdVenuesNewRouteImport
      parentRoute: typeof AppOrganiserRoute
    }
    '/_app/organiser/$orgId/events/new': {
      id: '/_app/organiser/$orgId/events/new'
      path: '/$orgId/events/new'
      fullPath: '/organiser/$orgId/events/new'
      preLoaderRoute: typeof AppOrganiserOrgIdEventsNewRouteImport
      parentRoute: typeof AppOrganiserRoute
    }
    '/_app/organiser/$orgId/events/$eventId/': {
      id: '/_app/organiser/$orgId/events/$eventId/'
      path: '/$orgId/events/$eventId'
      fullPath: '/organiser/$orgId/events/$eventId/'
      preLoaderRoute: typeof AppOrganiserOrgIdEventsEventIdIndexRouteImport
      parentRoute: typeof AppOrganiserRoute
    }
  }
}

interface AppOrganiserRouteChildren {
  AppOrganiserIndexRoute: typeof AppOrganiserIndexRoute
  AppOrganiserOrgIdIndexRoute: typeof AppOrganiserOrgIdIndexRoute
  AppOrganiserOrgIdEventsNewRoute: typeof AppOrganiserOrgIdEventsNewRoute
  AppOrganiserOrgIdVenuesNewRoute: typeof AppOrganiserOrgIdVenuesNewRoute
  AppOrganiserOrgIdEventsEventIdIndexRoute: typeof AppOrganiserOrgIdEventsEventIdIndexRoute
}

const AppOrganiserRouteChildren: AppOrganiserRouteChildren = {
  AppOrganiserIndexRoute: AppOrganiserIndexRoute,
  AppOrganiserOrgIdIndexRoute: AppOrganiserOrgIdIndexRoute,
  AppOrganiserOrgIdEventsNewRoute: AppOrganiserOrgIdEventsNewRoute,
  AppOrganiserOrgIdVenuesNewRoute: AppOrganiserOrgIdVenuesNewRoute,
  AppOrganiserOrgIdEventsEventIdIndexRoute:
    AppOrganiserOrgIdEventsEventIdIndexRoute,
}

const AppOrganiserRouteWithChildren = AppOrganiserRoute._addFileChildren(
  AppOrganiserRouteChildren,
)

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppOrganiserRoute: typeof AppOrganiserRouteWithChildren
  AppProfilePasskeysRoute: typeof AppProfilePasskeysRoute
  AppTicketsTicketIdRoute: typeof AppTicketsTicketIdRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
  AppHomeIndexRoute: typeof AppHomeIndexRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
  AppTicketsIndexRoute: typeof AppTicketsIndexRoute
  AppEventsEventIdCheckoutRoute: typeof AppEventsEventIdCheckoutRoute
  AppEventsEventIdQueueRoute: typeof AppEventsEventIdQueueRoute
  AppEventsEventIdIndexRoute: typeof AppEventsEventIdIndexRoute
  AppReservationsReservationIdIndexRoute: typeof AppReservationsReservationIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppOrganiserRoute: AppOrganiserRouteWithChildren,
  AppProfilePasskeysRoute: AppProfilePasskeysRoute,
  AppTicketsTicketIdRoute: AppTicketsTicketIdRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
  AppHomeIndexRoute: AppHomeIndexRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
  AppTicketsIndexRoute: AppTicketsIndexRoute,
  AppEventsEventIdCheckoutRoute: AppEventsEventIdCheckoutRoute,
  AppEventsEventIdQueueRoute: AppEventsEventIdQueueRoute,
  AppEventsEventIdIndexRoute: AppEventsEventIdIndexRoute,
  AppReservationsReservationIdIndexRoute:
    AppReservationsReservationIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthSetupRoute: typeof AuthSetupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthSetupRoute: AuthSetupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ConfirmEmailChangeRoute: ConfirmEmailChangeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
