"""create identity tables

Revision ID: 29ca6f230f31
Revises: 0001_identity_init
Create Date: 2026-07-03 19:54:14.722838

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "29ca6f230f31"
down_revision: Union[str, None] = "0001_identity_init"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=True),
        sa.Column("entity_id", sa.String(length=255), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("device_fingerprint_hash", sa.String(length=255), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("prev_hash", sa.LargeBinary(length=32), nullable=True),
        sa.Column("hash", sa.LargeBinary(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="audit",
    )
    op.create_index(
        op.f("ix_audit_audit_events_action"),
        "audit_events",
        ["action"],
        unique=False,
        schema="audit",
    )
    op.create_index(
        op.f("ix_audit_audit_events_actor_id"),
        "audit_events",
        ["actor_id"],
        unique=False,
        schema="audit",
    )
    op.create_index(
        op.f("ix_audit_audit_events_created_at"),
        "audit_events",
        ["created_at"],
        unique=False,
        schema="audit",
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("channel", sa.Enum("email", "sms", name="notification_channel"), nullable=False),
        sa.Column("template_key", sa.String(length=64), nullable=False),
        sa.Column("destination_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "sent", "failed", name="notification_status"),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="identity",
    )
    op.create_index(
        op.f("ix_identity_notifications_created_at"),
        "notifications",
        ["created_at"],
        unique=False,
        schema="identity",
    )
    op.create_index(
        op.f("ix_identity_notifications_status"),
        "notifications",
        ["status"],
        unique=False,
        schema="identity",
    )
    op.create_index(
        op.f("ix_identity_notifications_template_key"),
        "notifications",
        ["template_key"],
        unique=False,
        schema="identity",
    )
    op.create_index(
        op.f("ix_identity_notifications_user_id"),
        "notifications",
        ["user_id"],
        unique=False,
        schema="identity",
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("full_name_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("email_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("email_hash", sa.String(length=64), nullable=False),
        sa.Column("phone_number_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("phone_number_hash", sa.String(length=64), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("phone_number_verified", sa.Boolean(), nullable=False),
        sa.Column("email_verification_token", sa.String(length=255), nullable=True),
        sa.Column("email_verification_token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("phone_number_otp", sa.String(length=10), nullable=True),
        sa.Column("phone_number_otp_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pending_phone_number_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("pending_phone_number_hash", sa.String(length=64), nullable=True),
        sa.Column("pending_phone_otp", sa.String(length=10), nullable=True),
        sa.Column("pending_phone_otp_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pending_email_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("pending_email_hash", sa.String(length=64), nullable=True),
        sa.Column("pending_email_verification_token", sa.String(length=255), nullable=True),
        sa.Column("pending_email_token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("national_id_hash", sa.String(length=64), nullable=True),
        sa.Column("national_id_number", sa.Text(), nullable=True),
        sa.Column(
            "kyc_status",
            sa.Enum("not_submitted", "pending", "approved", "rejected", name="kyc_status"),
            nullable=False,
        ),
        sa.Column("kyc_document_object_key", sa.String(length=255), nullable=True),
        sa.Column("terms_accepted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("registration_ip", sa.String(length=45), nullable=False),
        sa.Column("device_fingerprint", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="identity",
    )
    op.create_index(
        op.f("ix_identity_users_email_hash"),
        "users",
        ["email_hash"],
        unique=True,
        schema="identity",
    )
    op.create_index(
        op.f("ix_identity_users_email_verification_token"),
        "users",
        ["email_verification_token"],
        unique=False,
        schema="identity",
    )
    op.create_index(
        op.f("ix_identity_users_national_id_hash"),
        "users",
        ["national_id_hash"],
        unique=True,
        schema="identity",
    )
    op.create_index(
        op.f("ix_identity_users_pending_email_hash"),
        "users",
        ["pending_email_hash"],
        unique=False,
        schema="identity",
    )
    op.create_index(
        op.f("ix_identity_users_pending_email_verification_token"),
        "users",
        ["pending_email_verification_token"],
        unique=False,
        schema="identity",
    )
    op.create_index(
        op.f("ix_identity_users_pending_phone_number_hash"),
        "users",
        ["pending_phone_number_hash"],
        unique=False,
        schema="identity",
    )
    op.create_index(
        op.f("ix_identity_users_phone_number_hash"),
        "users",
        ["phone_number_hash"],
        unique=True,
        schema="identity",
    )
    op.create_table(
        "device_fingerprints",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("fingerprint_hash", sa.String(length=255), nullable=False),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column(
            "seen_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("account_count_at_seen", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["identity.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="identity",
    )
    op.create_index(
        op.f("ix_identity_device_fingerprints_fingerprint_hash"),
        "device_fingerprints",
        ["fingerprint_hash"],
        unique=False,
        schema="identity",
    )
    op.create_index(
        op.f("ix_identity_device_fingerprints_user_id"),
        "device_fingerprints",
        ["user_id"],
        unique=False,
        schema="identity",
    )
    op.create_table(
        "devices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("public_key", sa.LargeBinary(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attestation_platform", sa.String(length=16), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["identity.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_key"),
        schema="identity",
    )
    op.create_index(
        op.f("ix_identity_devices_user_id"), "devices", ["user_id"], unique=False, schema="identity"
    )
    op.create_table(
        "passkey_credentials",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("credential_id", sa.LargeBinary(), nullable=False),
        sa.Column("public_key", sa.LargeBinary(), nullable=False),
        sa.Column("sign_count", sa.Integer(), nullable=False),
        sa.Column("aaguid", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["identity.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="identity",
    )
    op.create_index(
        op.f("ix_identity_passkey_credentials_credential_id"),
        "passkey_credentials",
        ["credential_id"],
        unique=True,
        schema="identity",
    )
    op.create_index(
        op.f("ix_identity_passkey_credentials_user_id"),
        "passkey_credentials",
        ["user_id"],
        unique=False,
        schema="identity",
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("jti", sa.String(length=36), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("device_fingerprint", sa.String(length=255), nullable=True),
        sa.Column("device_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_used_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_asserted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["identity.devices.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["identity.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="identity",
    )
    op.create_index(
        op.f("ix_identity_sessions_device_id"),
        "sessions",
        ["device_id"],
        unique=False,
        schema="identity",
    )
    op.create_index(
        op.f("ix_identity_sessions_jti"), "sessions", ["jti"], unique=True, schema="identity"
    )
    op.create_index(
        op.f("ix_identity_sessions_user_id"),
        "sessions",
        ["user_id"],
        unique=False,
        schema="identity",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_identity_sessions_user_id"), table_name="sessions", schema="identity")
    op.drop_index(op.f("ix_identity_sessions_jti"), table_name="sessions", schema="identity")
    op.drop_index(op.f("ix_identity_sessions_device_id"), table_name="sessions", schema="identity")
    op.drop_table("sessions", schema="identity")
    op.drop_index(
        op.f("ix_identity_passkey_credentials_user_id"),
        table_name="passkey_credentials",
        schema="identity",
    )
    op.drop_index(
        op.f("ix_identity_passkey_credentials_credential_id"),
        table_name="passkey_credentials",
        schema="identity",
    )
    op.drop_table("passkey_credentials", schema="identity")
    op.drop_index(op.f("ix_identity_devices_user_id"), table_name="devices", schema="identity")
    op.drop_table("devices", schema="identity")
    op.drop_index(
        op.f("ix_identity_device_fingerprints_user_id"),
        table_name="device_fingerprints",
        schema="identity",
    )
    op.drop_index(
        op.f("ix_identity_device_fingerprints_fingerprint_hash"),
        table_name="device_fingerprints",
        schema="identity",
    )
    op.drop_table("device_fingerprints", schema="identity")
    op.drop_index(
        op.f("ix_identity_users_phone_number_hash"), table_name="users", schema="identity"
    )
    op.drop_index(
        op.f("ix_identity_users_pending_phone_number_hash"), table_name="users", schema="identity"
    )
    op.drop_index(
        op.f("ix_identity_users_pending_email_verification_token"),
        table_name="users",
        schema="identity",
    )
    op.drop_index(
        op.f("ix_identity_users_pending_email_hash"), table_name="users", schema="identity"
    )
    op.drop_index(op.f("ix_identity_users_national_id_hash"), table_name="users", schema="identity")
    op.drop_index(
        op.f("ix_identity_users_email_verification_token"), table_name="users", schema="identity"
    )
    op.drop_index(op.f("ix_identity_users_email_hash"), table_name="users", schema="identity")
    op.drop_table("users", schema="identity")
    op.drop_index(
        op.f("ix_identity_notifications_user_id"), table_name="notifications", schema="identity"
    )
    op.drop_index(
        op.f("ix_identity_notifications_template_key"),
        table_name="notifications",
        schema="identity",
    )
    op.drop_index(
        op.f("ix_identity_notifications_status"), table_name="notifications", schema="identity"
    )
    op.drop_index(
        op.f("ix_identity_notifications_created_at"), table_name="notifications", schema="identity"
    )
    op.drop_table("notifications", schema="identity")
    op.drop_index(
        op.f("ix_audit_audit_events_created_at"), table_name="audit_events", schema="audit"
    )
    op.drop_index(op.f("ix_audit_audit_events_actor_id"), table_name="audit_events", schema="audit")
    op.drop_index(op.f("ix_audit_audit_events_action"), table_name="audit_events", schema="audit")
    op.drop_table("audit_events", schema="audit")
    # ### end Alembic commands ###
